apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: portainer
spec:
  template:
    spec:
      containers:
        - name: portainer
          image: portainer/portainer-ce:2.17.1
