apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: blog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: lukasrotermund.invalid
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: blog
            servicePort: 808