apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: blog
spec:
  rules:
    - host: lukasrotermund.invalid
      http:
        paths:
        - path: /
          backend:
            serviceName: blog
            servicePort: 80
  tls:
    - hosts:
      - 'lukasrotermund.invalid'