apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base/keycloak/
  - ./secrets
patches:
  - deployment.yaml

patchesJson6902:
  - path: hostname.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: keycloak
      namespace: keycloak
