apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kimkues-wp
  labels:
    app: kimkues-wp
spec:
  selector:
    matchLabels:
      app: kimkues-wp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kimkues-wp
        tier: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql
              key: name
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
