apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: kimkues-wp
  labels:
    app: kimkues-wp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi