apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kimkues-wp
  labels:
    app: kimkues-wp
spec:
  ports:
    - port: 3306
  selector:
    app: kimkues-wp
    tier: mysql
  clusterIP: None