apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgA7KT3o8xENl3yEHx035R2R5tS7/XinQ7tAN63u2enWdQMWg5YkbqaVS78jJd0TpLTccl0WGX2EOt7157fAq6MmWxujMHeuH3g/YamPn3NvF//P3+rNR97UWTP/a0lday/aGxen63JLis/e2sAz9RVkux/3oJ3vNAhs1Z8QPsbzExsj8fK9ZFd/1ocME4qePX6mz5KfPyqdWaVeEG4m7UbEsqKs24HSpbxvUF7fUbn7XwiNLVxQm8Sx9sD2uEWqtFKQnlr6odQYLNNN9k3b83bW3GIYyFiF7viewLDoyyCvsX8+mBbJa5If7pCG1fHOrg5Djskj5I+BMt/sVkiY5w3EWkSzX0C7qpvcf3Gxb0m7k6+RROntBmf/rMxCSoT8sXVIG2qZWRIjh2g3baBjkhWnWYuQfIeErEksnGknyJBOOzrZa0gE0IizEEAD/p/7YIDUaFmezDZI3VkNj65PCwtnvRyvwRZ8EtnjKLNC8x2rTEKymtaT//YtPvBddhoUJF00aW/17b+3MxT74OLvJy/E3pTsjKNrDi4osrvQRBMRRhXJndpI6PYCn5WqBm0JkoRwuWa/KKT5tS2X9z8DS13FlJr0W1WG7A58B52oO3it3dJCK8+fBsYXS33ntOycCHlcVTtkK01ztC6EiL+pK3wfS8hOusxdUBEEYNUbQYg0fg2FRte7ur/1yf/2WMSbsmf6EG7+PE4fRjxK1u91g+RmvdLEhUldoYk6/sBeqwAAut/WcNLnLQsM
    user: AgDasnhGeCqNHuy8CCqEh9aJLWMm159qn/ijxHKmhTZWfJo12v4WybleJLP14OyXE51mGKCVPpoX9pr9EcjJypygm/B4E8VjQ4W0+WC/O5y4QVUiJ+azfhK+FZvW2kJSI3jIg5qN16qj/8vdiEKO4dzrHQbSWHdy2Rf6PBpWC7c/caWo3u9mHzg3J1COrkPr+QXk7f7+yMEPhcz6/zAdsUPYWmA5QxnNRPhepyzB8Qy+CUtn3CHUDbfuXjYdSTqj6PWYLuLXOz0fHuqCDOiQjM3rOF/lKh7CGA+Z3EoOrZKSFKpC1d+BQcijqvVuuDOrNseLhR5F3I4UfxnI1eWzmeE/I8Q2GAOMDuxarO42786qb56n7OPv5LNKqL3mbzrWmzsqs2YOFBK5V4N3qWwupaw9XgGg7fW4UTpUV5+d//jjyOTb8eVKXG5zvp8I5pKeXLA3LszUUhVagUfVihnfrQfHmwBiYZDgZC3c3RniRL6opt9ZRWXagwZStePP5MSsZ2g0Xuo9KG0eLs0/IFQ4uWI7rhX3ZDFo+74GHxRiRVMJ7mpR1eJBpShBaRBNYUalVOflruTLwg4W0NslkQMnQYvnc1P63cMGee6JXKaj/So/+v6l85G0ezSRTYVYHp8N6xs1KjMEX47DvWMKMjP9ZKxcPqtCfAF4hZ/s0xrri/gAeJ1vFPIohAJ5ufUwJ/J3qbpjzlC2kkZWhj/Rz0w=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: admin
      namespace: keycloak

